import os
import json
import uuid
import logging
from flask import Flask, request, jsonify, send_from_directory

from core import region_detector
from core.disease_detector import detect_with_both, map_hf_to_standard
from core.doctor_finder import find_nearby_doctors
from core import mobilenet_detector
from core import chat_engine

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__, static_folder="static")
app.config["MAX_CONTENT_LENGTH"] = 16 * 1024 * 1024
UPLOAD_FOLDER = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static", "uploads")
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")


def load_json(filename):
    path = os.path.join(DATA_DIR, filename)
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


DISEASES = load_json("diseases.json")
TREATMENTS = load_json("treatments.json")
FOODS = load_json("foods.json")
OCCURRENCE = load_json("occurrence.json")
CONTAGIOUS = load_json("contagious.json")
REGION_MAP = load_json("region_disease_map.json")

DISCLAIMER = (
    "This diagnosis is generated by an AI model and is for informational purposes only. "
    "It is NOT a substitute for professional medical advice. Always consult a qualified "
    "dermatologist or healthcare professional for proper diagnosis and treatment."
)

EMERGENCY_WARNING = (
    "SEEK IMMEDIATE MEDICAL ATTENTION IF: rapid spreading, severe pain or swelling, "
    "fever, pus or drainage, or if the condition is melanoma/skin cancer."
)


@app.route("/")
def index():
    return send_from_directory("static", "index.html")


@app.route("/diagnose", methods=["POST"])
def diagnose():
    if "image" not in request.files:
        return jsonify({"success": False, "error": "No image uploaded"}), 400

    file = request.files["image"]
    if file.filename == "":
        return jsonify({"success": False, "error": "No file selected"}), 400

    region = request.form.get("region", "").strip().lower()
    location = request.form.get("location", "").strip()

    if region not in region_detector.REGIONS:
        return jsonify({"success": False, "error": f"Unknown region: {region}"}), 400

    ext = os.path.splitext(file.filename)[1] or ".jpg"
    img_name = str(uuid.uuid4()) + ext
    img_path = os.path.join(UPLOAD_FOLDER, img_name)
    file.save(img_path)

    try:
        from PIL import Image
        img = Image.open(img_path).convert("RGB")

        # STEP 1: REGION VALIDATION
        valid, message = region_detector.validate_region(img, region)
        if not valid:
            return jsonify({"success": False, "region_mismatch": True, "message": message})

        # Detect what region the image actually contains
        detected_type = region_detector.detect_region_type(img)

        # STEP 2: DISEASE DETECTION (DUAL MODELS)
        detection = detect_with_both(img)

        # STEP 2b: ADDITIONAL DETECTOR (new 23-class model)
        mn = mobilenet_detector.predict(img)

        # STEP 3: CHECK IF NORMAL/HEALTHY SKIN
        if detection["is_normal"]:
            region_label = REGION_MAP.get(region, {}).get("region_label", region.title())
            return jsonify({
                "success": True,
                "normal": True,
                "disease_name": "Healthy / Normal Skin",
                "message": f"Do not panic! Your {region_label.lower()} appears CLEAR and HEALTHY.",
                "confidence": detection["combined_confidence"],
                "primary": detection["primary_label"],
                "primary_conf": detection["primary_confidence"],
                "secondary": detection["secondary_label"],
                "secondary_conf": detection["secondary_confidence"],
                "agreed": detection["agreed"],
                "mobilenet": mn,
                "disclaimer": DISCLAIMER,
            })

        # STEP 4: LOOK UP DISEASE DETAILS
        std_key = map_hf_to_standard(detection["final_label"])
        if std_key is None:
            std_key = "healthy_normal"

        # If new model strongly detects a common condition (acne / hyperpigmentation)
        # that fits the selected body region, prefer it over the models' closest guess.
        overridden = False
        if mn and mn.get("std_key") in ("acne", "hyperpigmentation") \
                and mn.get("confidence", 0) >= 0.5 \
                and mn["std_key"] in REGION_MAP.get(region, {}).get("diseases", []):
            std_key = mn["std_key"]
            overridden = True

        disease_info = DISEASES.get(std_key, {})
        treatment_info = TREATMENTS.get(std_key, {})
        food_info = FOODS.get(std_key, {})
        occurrence_info = OCCURRENCE.get(std_key, {})
        contagious_info = CONTAGIOUS.get(std_key, {})

        # STEP 5: DOCTOR FINDER
        doctors = []
        if location:
            doc_result = find_nearby_doctors(location=location)
            doctors = doc_result.get("doctors", [])

        region_label = REGION_MAP.get(region, {}).get("region_label", region.title())

        return jsonify({
            "success": True,
            "normal": False,
            "region": region,
            "region_label": region_label,
            "disease_name": disease_info.get("name", std_key.replace("_", " ").title()),
            "confidence": detection["combined_confidence"],
            "primary": detection["primary_label"],
            "primary_conf": detection["primary_confidence"],
            "secondary": detection["secondary_label"],
            "secondary_conf": detection["secondary_confidence"],
            "agreed": detection["agreed"],
            "model_basis": "new_model" if overridden else "dual",
            "mobilenet": mn,
            "description": disease_info.get("description", ""),
            "symptoms": disease_info.get("symptoms", []),
            "causes": disease_info.get("causes", []),
            "severity": disease_info.get("severity", ""),
            "common_regions": disease_info.get("common_regions", []),
            "occurrence": occurrence_info,
            "contagious": contagious_info,
            "treatments": treatment_info,
            "foods": food_info,
            "doctors": doctors,
            "disclaimer": DISCLAIMER,
            "emergency_warning": EMERGENCY_WARNING,
        })

    except Exception as e:
        logger.exception("Diagnosis error")
        return jsonify({"success": False, "error": f"Processing failed: {str(e)}"}), 500


@app.route("/normal-method", methods=["GET"])
def normal_method():
    return jsonify({"message": "For a normal/healthy check, upload an image and if the "
                               "model confidence is below threshold it will report 'Healthy skin'."})


@app.route("/chat", methods=["POST"])
def chat():
    data = request.get_json(silent=True) or {}
    question = (data.get("question") or "").strip()
    if not question:
        return jsonify({"success": False, "error": "Please enter a question."}), 400

    result = chat_engine.chat(question)
    return jsonify(result)


if __name__ == "__main__":
    print("=" * 60)
    print("  SKIN DISEASE DETECTOR - METHOD 1 (Image Diagnosis)")
    print("  Open: http://localhost:5000")
    print("=" * 60)
    app.run(host="127.0.0.1", port=5000, debug=False)